Repository saero-jinro/saerojinro-server, pull requests merged in 2025-03, with the labels that each got.

#12 feature/#10 유저 도메인 작성 및 관리자 등록 구현
  .github/workflows/pull-request-test-coverage.yml
  build.gradle
  codecov.yml
  jacoco.gradle
  saerojinro-admin/build.gradle
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/SaerojinroAdminApplication.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/AdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/config/InfraConfig.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/presentation/AdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/presentation/AdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/presentation/request/AdminCreateRequest.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/presentation/response/AdminPersistResponse.java
  saerojinro-admin/src/main/resources/application-local.yml
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-admin/src/testFixtures/java/admin/application/AdminFacadeTest.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/config/SecurityConfig.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/BaseRole.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/BaseTimeEntity.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/Category.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/Provider.java
  saerojinro-domain/build.gradle
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/User.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/UserRepository.java
  saerojinro-domain/src/testFixtures/java/mock/TestEntityUtils.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  saerojinro-domain/src/testFixtures/java/user/UserDomainTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserCommandServiceTest.java
  saerojinro-infra/build.gradle
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/EnableSaeroJinroConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/SaeroJinroConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/SaeroJinroConfigGroup.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/SaeroJinroConfigImportSelector.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/JpaAuditingConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/JpaConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/PropertiesConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/UserRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/UserJpaRepository.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/SaerojinroSpeakerApplication.java
Labels: feature

#13 feature/#11 강의 도메인 작성 및 모듈간 의존성 추가
  saerojinro-api/src/main/resources/application-local.yml
  saerojinro-api/src/main/resources/application.yml
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/BaseTimeEntity.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/LectureRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/enums/LectureStatus.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LectureRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
  saerojinro-speaker/src/main/resources/application-local.yml
  saerojinro-speaker/src/main/resources/application.yml
Labels: feature

#17 feature/#14 관리자 로그인 구현
  saerojinro-auth/build.gradle
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/SaerojinroAuthApplication.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/application/AuthFacade.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/config/InfraConfig.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/presentation/AuthController.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/presentation/AuthControllerImpl.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/presentation/request/EmailLoginRequest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/presentation/response/JwtResponse.java
  saerojinro-auth/src/main/resources/application-local.yml
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-auth/src/testFixtures/java/auth/AuthFacadeTest.java
  saerojinro-common/build.gradle
  saerojinro-common/src/main/java/goorm/saerojinro/common/config/SecurityConfig.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/filter/JwtAuthenticationFilter.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/JwtProperties.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/JwtProvider.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/exception/JwtExceptionCode.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/exception/JwtExpiredException.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/exception/JwtInvalidException.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/exception/JwtMalformedException.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/exception/JwtSignatureInvalidException.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/exception/JwtUnsupportedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/User.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/UserRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/exception/InvalidPasswordException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/exception/UserDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/exception/UserNotFoundException.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  saerojinro-domain/src/testFixtures/java/user/UserDomainTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/UserRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/UserJpaRepository.java
  settings.gradle
Labels: feature

#23 feature/#18 #20 강의 조회 및 생성
  saerojinro-api/build.gradle
  saerojinro-api/src/main/java/goorm/saerojinro/api/config/InfraConfig.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/api/LectureFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureListResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponse.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/LectureRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/exception/LectureDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/exception/LectureNotFoundException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/UserRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/exception/InvalidUserRoleException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/exception/UserDomainExceptionCode.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLectureRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  saerojinro-domain/src/testFixtures/java/notification/NotificationDomainTest.java
  saerojinro-domain/src/testFixtures/java/notification/application/NotificationCommandServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LectureRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/UserRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
  saerojinro-speaker/build.gradle
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/SpeakerLectureFacade.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/config/InfraConfig.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/presentation/SpeakerController.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/presentation/request/LectureCreateRequest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/presentation/response/LectureCreateResponse.java
Labels: feature

#25 Feat/#22 SSE를 이용한 알림 전송
  jacoco.gradle
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/application/NotificationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/exception/EmitterNotFoundException.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/exception/NotificationApiExceptionCode.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/request/NotificationSendRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/response/NotificationSendResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/response/ReceivedNotificationListResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/response/ReceivedNotificationResponse.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/application/NotificationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/domain/EmitterRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/domain/Notification.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/domain/NotificationRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/User.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeNotificationRepository.java
  saerojinro-domain/src/testFixtures/java/notification/NotificationDomainTest.java
  saerojinro-domain/src/testFixtures/java/notification/application/NotificationCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/notification/application/NotificationQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/EmitterRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/NotificationRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/NotificationJpaRepository.java
Labels: feature

#27 feat/#9 예약 도메인 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/api/ReservationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/response/ReservationCancelResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/response/ReservationCreateResponse.java
  saerojinro-api/src/testFixtures/java/reservation/ReservationFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/Reservation.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/ReservationRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/exception/ReservationDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/exception/ReservationExistException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/exception/ReservationNotFoundException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReservationRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/ReservationDomainTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReservationRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReservationJpaRepository.java
Labels: feature

#24 feature/#21 카카오 소셜 로그인
  jacoco.gradle
  saerojinro-auth/build.gradle
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/application/AuthFacade.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/config/OidcConfig.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/presentation/AuthController.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/presentation/AuthControllerImpl.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/presentation/request/SocialLoginRequest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/OidcTokenValidator.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/dto/SocialUserProfile.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/exception/OidcExceptionCode.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/exception/OidcExpiredException.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/exception/OidcInvalidAudienceException.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/exception/OidcInvalidIdTokenException.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/exception/OidcInvalidIssuerException.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/google/GoogleOidcProperties.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/kakao/KakaoOidcProperties.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/kakao/KakaoOidcTokenValidator.java
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-auth/src/testFixtures/java/auth/AuthFacadeTest.java
  saerojinro-auth/src/testFixtures/java/auth/mock/FakeKakaoOidcTokenValidator.java
  saerojinro-domain/build.gradle
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/User.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/UserRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  saerojinro-domain/src/testFixtures/java/user/UserDomainTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserCommandServiceTest.java
  saerojinro-infra/build.gradle
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/UserRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/UserJpaRepository.java
Labels: feature

#31 refactor/#30 도메인 계층 분리 및 강의 상세조회 응답 필드 추가
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/SpeakerLectureFacade.java
Labels: refactor

#32 feat/#28 알림 전송을 위한 로직 추가 작성 및 테스트
  build.gradle
  jacoco.gradle
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/application/NotificationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/request/NotificationSendRequest.java
  saerojinro-api/src/testFixtures/java/notification/application/NotificationFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/domain/EmitterRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/domain/NotificationRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/ReservationRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeNotificationRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReservationRepository.java
  saerojinro-domain/src/testFixtures/java/notification/NotificationDomainTest.java
  saerojinro-domain/src/testFixtures/java/notification/application/NotificationCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/notification/application/NotificationQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/EmitterRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReservationRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReservationJpaRepository.java
Labels: feature

#36 feature/#33 유저 정보 수정 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/application/UserFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/UserController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/UserControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/request/UserUpdateRequest.java
  saerojinro-api/src/testFixtures/java/user/UserFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/exception/UserDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/exception/UserNotAuthenticatedException.java
  saerojinro-domain/src/testFixtures/java/user/application/UserCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
Labels: feature

#38 feature/#37 유저 삭제 기능 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/application/UserFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/UserController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/UserControllerImpl.java
  saerojinro-api/src/testFixtures/java/user/UserFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/User.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/UserRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeUserRepository.java
  saerojinro-domain/src/testFixtures/java/user/application/UserCommandServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/UserRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/UserJpaRepository.java
Labels: feature

#40 feature/#34 강의 수정 기능 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationController.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/exception/LectureDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/exception/SpeakerMissmatchException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-speaker/build.gradle
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/SpeakerLectureFacade.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/presentation/SpeakerController.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/presentation/SpeakerControllerImpl.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/presentation/request/LectureUpdateRequest.java
  saerojinro-speaker/src/testFixtures/java/speaker/api/SpeakerLectureFacadeTest.java
Labels: feature

#41 feature/#39 reissue 기능 구현
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-api/src/main/resources/application.yml
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/application/AuthFacade.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/AuthController.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/AuthControllerImpl.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/request/EmailLoginRequest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/request/ReissueRequest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/request/SocialLoginRequest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/response/JwtResponse.java
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-auth/src/testFixtures/java/auth/AuthFacadeTest.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/JwtProvider.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reissue/application/RefreshTokenService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reissue/domain/RefreshToken.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reissue/domain/RefreshTokenRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reissue/exception/RefreshTokenNotFoundException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reissue/exception/ReissueExceptionCode.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeRefreshTokenRepository.java
  saerojinro-domain/src/testFixtures/java/reissue/RefreshTokenDomainTest.java
  saerojinro-domain/src/testFixtures/java/reissue/application/RefreshTokenServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/RedisConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/RefreshTokenRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/redis/RedisRefreshTokenRepository.java
  saerojinro-speaker/src/main/resources/application.yml
Labels: feature

#43 feature/#42 로그 설정
  jacoco.gradle
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/application/AdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/aspect/ExceptionLoggingAspect.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/aspect/ServerErrorLoggingAspect.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/presentation/AdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/presentation/AdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/presentation/request/AdminCreateRequest.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/presentation/response/AdminPersistResponse.java
  saerojinro-admin/src/testFixtures/java/admin/application/AdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/aspect/ExceptionLoggingAspect.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/aspect/ServerErrorLoggingAspect.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureControllerImpl.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/aspect/ExceptionLoggingAspect.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/aspect/ServerErrorLoggingAspect.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/config/WebConfig.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/log/annotation/NoLogging.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/log/interceptor/LoggingInterceptor.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/log/util/HttpReqResUtils.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/log/util/LoggingUtils.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/application/SpeakerLectureFacade.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/aspect/ExceptionLoggingAspect.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/aspect/ServerErrorLoggingAspect.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerController.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerControllerImpl.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/request/LectureCreateRequest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/request/LectureUpdateRequest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/response/LectureCreateResponse.java
  saerojinro-speaker/src/testFixtures/java/speaker/api/SpeakerLectureFacadeTest.java
Labels: feature

#46 feature/#44 swagger 설정
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/config/SwaggerConfig.java
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-api/src/main/java/goorm/saerojinro/api/config/SwaggerConfig.java
  saerojinro-api/src/main/resources/application.yml
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/config/SwaggerConfig.java
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/config/SwaggerConfig.java
  saerojinro-speaker/src/main/resources/application.yml
Labels: feature

#51 Feat/#29 feature 즐겨찾기 기능 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/api/WishListFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/response/WishListCreateResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/response/WishListDeleteResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/response/WishListResponse.java
  saerojinro-api/src/testFixtures/java/wishList/WishListFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/application/WishListCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/application/WishListQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/domain/WishList.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/domain/WishListRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/exception/WishListDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/exception/WishListExistException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/exception/WishListNotFoundException.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeWishListRepository.java
  saerojinro-domain/src/testFixtures/java/wishlist/WishListDomainTest.java
  saerojinro-domain/src/testFixtures/java/wishlist/application/WishListCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/wishlist/application/WishListQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/WishListRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/WishListJpaRepository.java
Labels: feature

#54 refactor/#52 중복 코드 및 불필요한 코드 제거
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/api/ReservationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/response/ReservationCreateResponse.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReservationRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReservationJpaRepository.java
Labels: refactor

#47 feat/#35 event handler 생성
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/application/NotificationEventHandler.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/application/NotificationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/request/NotificationSendRequest.java
  saerojinro-api/src/main/resources/application.yml
  saerojinro-api/src/testFixtures/java/notification/application/NotificationEventHandlerTest.java
  saerojinro-api/src/testFixtures/java/notification/application/NotificationFacadeTest.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/event/CommonEvent.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/event/EventType.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeNotificationRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/notification/sse/NotificationSseSender.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/notification/sse/response/NotificationSendResponse.java
Labels: feature

#48 feature/#45 강의 삭제 기능
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/enums/LectureStatus.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/exception/LectureDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/exception/LectureNotAuthorizedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/exception/SpeakerMissmatchException.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/application/SpeakerLectureFacade.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerController.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerControllerImpl.java
  saerojinro-speaker/src/testFixtures/java/speaker/api/SpeakerLectureFacadeTest.java
Labels: feature

#58 feature/#57 유저 권한 수정 기능 구현
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/application/AdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/presentation/AdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/presentation/AdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/presentation/request/RoleUpdateRequest.java
  saerojinro-admin/src/testFixtures/java/admin/application/AdminFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserCommandService.java
  saerojinro-domain/src/testFixtures/java/user/application/UserCommandServiceTest.java
Labels: feature

#60 feature/#59 로그아웃 기능 구현
  build.gradle
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/application/AuthFacade.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/AuthController.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/AuthControllerImpl.java
  saerojinro-auth/src/testFixtures/java/auth/AuthFacadeTest.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/config/SecurityConfig.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/blacklist/application/BlackListService.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/blacklist/domain/BlackListRepository.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/blacklist/exception/BlackListExceptionCode.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/blacklist/exception/BlackListedTokenException.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/reissue/application/RefreshTokenService.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/reissue/domain/RefreshToken.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/reissue/domain/RefreshTokenRepository.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/reissue/exception/RefreshTokenNotFoundException.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/reissue/exception/ReissueExceptionCode.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/filter/JwtAuthenticationFilter.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/JwtProvider.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeBlackListRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeRefreshTokenRepository.java
  saerojinro-domain/src/testFixtures/java/reissue/RefreshTokenDomainTest.java
  saerojinro-domain/src/testFixtures/java/reissue/application/RefreshTokenServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/BlackListRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/RefreshTokenRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/redis/RedisBlackListRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/redis/RedisRefreshTokenRepository.java
Labels: feature

#61 refactor/#50 notification moduling
  saerojinro-admin/build.gradle
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/application/NotificationAdminEventHandler.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/application/NotificationAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/exception/EmitterNotFoundException.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/exception/NotificationApiExceptionCode.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/presentation/NotificationAdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/presentation/NotificationAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/presentation/request/NotificationSendRequest.java
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationAdminEventHandlerTest.java
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/application/NotificationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationControllerImpl.java
  saerojinro-api/src/testFixtures/java/notification/application/NotificationFacadeTest.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/event/CommonEvent.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/notification/response/NotificationSendResponse.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/notification/sse/NotificationSseSender.java
Labels: refactor

#65 refactor/#50 알림 모듈링 추가 구현
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/application/NotificationAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/presentation/NotificationAdminControllerImpl.java
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationAdminEventHandlerTest.java
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/application/NotificationFacade.java
  saerojinro-api/src/testFixtures/java/notification/application/NotificationFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/application/EmitterQueryService.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeEmitterRepository.java
  saerojinro-domain/src/testFixtures/java/notification/application/EmitterQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/notification/sse/NotificationSseSender.java
Labels: refactor

#67 refactor/#66 강연자 -> 운영자 모듈 이동 및 로직 변경
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/application/LectureAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/presentation/LectureAdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/presentation/LectureAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/presentation/request/LectureCreateRequest.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/presentation/request/LectureUpdateRequest.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/presentation/response/LectureCreateResponse.java
  saerojinro-admin/src/testFixtures/java/lecture.application/LectureAdminFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/application/SpeakerLectureFacade.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerController.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerControllerImpl.java
  saerojinro-speaker/src/testFixtures/java/speaker/api/SpeakerLectureFacadeTest.java
Labels: refactor

#64 feature/#26 review 기능 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/application/ReviewFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/ReviewController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/ReviewControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/request/ReviewCreateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/request/ReviewUpdateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/response/ReviewCreateResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/response/ReviewListResponse.java
  saerojinro-api/src/testFixtures/java/review/ReviewFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/application/ReviewCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/application/ReviewQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/domain/Review.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/domain/ReviewRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/exception/ReviewDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/exception/ReviewNotAuthorizedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/exception/ReviewNotFoundException.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReviewRepository.java
  saerojinro-domain/src/testFixtures/java/review/ReviewDomainTest.java
  saerojinro-domain/src/testFixtures/java/review/application/ReviewCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/review/application/ReviewQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReviewRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReviewJpaRepository.java
Labels: feature

#74 refactor/#70 강의 생성 로직 변경
  codecov.yml
  jacoco.gradle
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/application/LectureAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/presentation/request/LectureCreateRequest.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/presentation/response/LectureCreateResponse.java
  saerojinro-admin/src/testFixtures/java/lecture.application/LectureAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponse.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-api/src/testFixtures/java/reservation/ReservationFacadeTest.java
  saerojinro-api/src/testFixtures/java/review/ReviewFacadeTest.java
  saerojinro-api/src/testFixtures/java/wishList/WishListFacadeTest.java
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/enums/LectureStatus.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/application/SpeakerCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/application/SpeakerQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/domain/Speaker.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/domain/SpeakerRepository.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLectureRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeSpeakerRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/ReservationDomainTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/review/ReviewDomainTest.java
  saerojinro-domain/src/testFixtures/java/review/application/ReviewCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/review/application/ReviewQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/speaker/SpeakerDomainTest.java
  saerojinro-domain/src/testFixtures/java/speaker/application/SpeakerCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/wishlist/WishListDomainTest.java
  saerojinro-domain/src/testFixtures/java/wishlist/application/WishListCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/wishlist/application/WishListQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/SpeakerRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/SpeakerJpaRepository.java
  saerojinro-speaker/build.gradle
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/SaerojinroSpeakerApplication.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/application/SpeakerLectureFacade.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/aspect/ExceptionLoggingAspect.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/aspect/ServerErrorLoggingAspect.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/config/InfraConfig.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/config/SwaggerConfig.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerController.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/SpeakerControllerImpl.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/request/LectureCreateRequest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/request/LectureUpdateRequest.java
  saerojinro-speaker/src/main/java/goorm/saerojinro/speaker/api/presentation/response/LectureCreateResponse.java
  saerojinro-speaker/src/main/resources/application-local.yml
  saerojinro-speaker/src/main/resources/application.yml
  saerojinro-speaker/src/testFixtures/java/speaker/api/SpeakerLectureFacadeTest.java
  settings.gradle
Labels: refactor

#72 feature/#68 사전 질문 기능 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/application/QuestionsFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/QuestionsController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/QuestionsControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/request/QuestionsCreateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/request/QuestionsUpdateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/response/QuestionsCreateResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/response/QuestionsListResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/application/ReservationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/application/WishListFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListControllerImpl.java
  saerojinro-api/src/testFixtures/java/questions/QuestionsFacadeTest.java
  saerojinro-api/src/testFixtures/java/reservation/ReservationFacadeTest.java
  saerojinro-api/src/testFixtures/java/wishList/WishListFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/application/QuestionsCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/application/QuestionsQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/domain/Questions.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/domain/QuestionsRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/exception/QuestionsDomainErrorCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/exception/QuestionsNotAuthorizedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/exception/QuestionsNotFoundException.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeQuestionsRepository.java
  saerojinro-domain/src/testFixtures/java/question/QuestionsDomainTest.java
  saerojinro-domain/src/testFixtures/java/question/application/QuestionsCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/question/application/QuestionsQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/QuestionsRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/QuestionsJpaRepository.java
Labels: feature

#77 refactor/#74 스웨거 설정파일 변경 및 트랜잭션 설정 추가
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/config/SwaggerConfig.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/application/LectureAdminFacade.java
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-api/src/main/java/goorm/saerojinro/api/config/SwaggerConfig.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-api/src/main/resources/application.yml
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/config/SwaggerConfig.java
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/application/SpeakerCommandService.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
Labels: refactor

#75 feature/#71 알림 스케줄러
  jacoco.gradle
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/config/InfraConfig.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/application/NotificationAdminEventHandler.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/application/NotificationScheduler.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/presentation/NotificationAdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/notification/presentation/NotificationAdminControllerImpl.java
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationAdminEventHandlerTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/config/InfraConfig.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/config/InfraConfig.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/event/CommonEvent.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/event/EventType.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/LectureRepository.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLectureRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/SaeroJinroConfigGroup.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/SchedulingConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LectureRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
Labels: chore

#78 feature/#69 로그 이벤트 저장 로직
  jacoco.gradle
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/lecture/application/LectureAdminFacade.java
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-api/src/main/resources/application.yml
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-common/src/main/java/goorm/saerojinro/common/config/SecurityConfig.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/Category.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/application/LogEventService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/LogEvent.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/LogEventProducer.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/LogEventRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/dto/LogEventDto.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/enums/LogEventType.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/logevent/application/LogEventServiceTest.java
  saerojinro-domain/src/testFixtures/java/logevent/domain/LogEventDomainTest.java
  saerojinro-domain/src/testFixtures/java/mock/producer/FakeLogEventProducer.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLogEventRepository.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/RedisConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/RedisProperties.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/messaging/eventlog/LogEventProducerImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/messaging/eventlog/RedisStreamListener.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/messaging/exception/InvalidMessageFormatException.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/messaging/exception/RedisMessagingExceptionCode.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/messaging/exception/StreamProcessingException.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LogEventRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/EventLogJpaRepository.java
Labels: feature

#83 refactor/#80 reviews 삭제
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/application/QuestionsFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/QuestionsControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/application/ReviewFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/ReviewController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/ReviewControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/request/ReviewCreateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/request/ReviewUpdateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/response/ReviewCreateResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/review/presentation/response/ReviewListResponse.java
  saerojinro-api/src/testFixtures/java/review/ReviewFacadeTest.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/config/SecurityConfig.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/application/QuestionsCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/application/ReviewCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/application/ReviewQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/domain/Review.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/domain/ReviewRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/exception/ReviewDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/exception/ReviewNotAuthorizedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/review/exception/ReviewNotFoundException.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReviewRepository.java
  saerojinro-domain/src/testFixtures/java/review/ReviewDomainTest.java
  saerojinro-domain/src/testFixtures/java/review/application/ReviewCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/review/application/ReviewQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReviewRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReviewJpaRepository.java
Labels: refactor

#86 feature/#79 시간표 조회
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/response/ReceivedNotificationListResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/response/ReceivedNotificationResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/application/TimetableFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/presentation/TimetableController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/presentation/TimetableControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/presentation/response/ReservationListResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/presentation/response/TimetableResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/presentation/response/WishlistListResponse.java
  saerojinro-api/src/testFixtures/java/timetable/TimetableFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/ReservationRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReservationRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeSpeakerRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/RedisConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReservationRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReservationJpaRepository.java
Labels: feature

#90 feature/#81 예약 등록 검증 로직 변경
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationAdminEventHandlerTest.java
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationUserAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/application/ReservationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/response/ReservationCancelResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/application/TimetableFacade.java
  saerojinro-api/src/testFixtures/java/reservation/ReservationFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/Reservation.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/ReservationRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReservationRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/ReservationDomainTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReservationRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReservationJpaRepository.java
Labels: feature

#96 refactor/#95 즐겨찾기 로직 최적화
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/application/QuestionsFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/application/ReservationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/application/WishListFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/response/WishListDeleteResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/response/WishListDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/response/WishListResponse.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-api/src/testFixtures/java/wishList/WishListFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/application/LogEventService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/application/WishListQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/domain/WishListRepository.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeWishListRepository.java
  saerojinro-domain/src/testFixtures/java/wishlist/application/WishListQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/WishListRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/WishListJpaRepository.java
Labels: refactor

#92 feature/#87 파일 저장 및 강의 생성 로직 수정
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/application/FileAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/FileAdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/FileAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/request/FileSaveRequest.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/response/FileReadResponse.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/response/FileSaveResponse.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/application/LectureAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/request/LectureCreateRequest.java
  saerojinro-admin/src/testFixtures/java/file/application/FileAdminFacadeTest.java
  saerojinro-admin/src/testFixtures/java/lecture.application/LectureUserAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponseByDate.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/application/FileCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/application/FileQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/application/FileStorageService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/domain/File.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/domain/FileRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/exception/FileDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/exception/FileDownloadFailedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/exception/FileNotFoundException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/exception/FileSaveFailedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/exception/FileSizeRetrievalFailedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/application/SpeakerCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/domain/Speaker.java
  saerojinro-domain/src/testFixtures/java/file/FileDomainTest.java
  saerojinro-domain/src/testFixtures/java/file/application/FileCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/file/application/FileQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/file/application/FileStorageServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/logevent/application/LogEventServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeFileRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeSpeakerRepository.java
  saerojinro-domain/src/testFixtures/java/speaker/SpeakerDomainTest.java
  saerojinro-domain/src/testFixtures/java/speaker/application/SpeakerCommandServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/FileRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/FileJpaRepository.java
Labels: feature

#99 feature/#93 운영자 대시보드 데이터
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/application/DashboardFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/application/DashboardScheduler.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/DashboardController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/DashboardControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/response/DashboardResponse.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/response/LectureRankResponse.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/response/TimeRankResponse.java
  saerojinro-admin/src/testFixtures/java/dashboard/DashboardFacadeTest.java
  saerojinro-admin/src/testFixtures/java/dashboard/DashboardSchedulerTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/dashboard/application/DashboardService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/dashboard/domain/Dashboard.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/dashboard/domain/DashboardRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/dashboard/dto/DashboardAggregation.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/ReservationRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/dto/LectureReservationCountDto.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/application/WishListQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/domain/WishListRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/dto/LectureWishlistCountDto.java
  saerojinro-domain/src/testFixtures/java/dashboard/DashboardDomainTest.java
  saerojinro-domain/src/testFixtures/java/dashboard/application/DashboardServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeDashboardRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReservationRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeWishListRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/wishlist/application/WishListQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/DashboardRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReservationRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/WishListRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/ReservationJpaRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/WishListJpaRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/redis/RedisDashboardRepository.java
Labels: feature

#97 refactor/#91 질문 조회 반환 리팩토링
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/application/QuestionFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/QuestionController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/QuestionControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/request/QuestionCreateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/request/QuestionUpdateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/response/QuestionCreateResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/response/QuestionListResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/response/QuestionResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/application/QuestionsFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/QuestionsControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/response/QuestionsCreateResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/questions/presentation/response/QuestionsListResponse.java
  saerojinro-api/src/testFixtures/java/question/QuestionFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/application/QuestionCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/application/QuestionQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/domain/Question.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/domain/QuestionRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/exception/QuestionDomainErrorCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/exception/QuestionNotAuthorizedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/exception/QuestionNotFoundException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/application/QuestionsCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/application/QuestionsQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/domain/QuestionsRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/exception/QuestionsNotAuthorizedException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/questions/exception/QuestionsNotFoundException.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeQuestionRepository.java
  saerojinro-domain/src/testFixtures/java/question/QuestionsDomainTest.java
  saerojinro-domain/src/testFixtures/java/question/application/QuestionsCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/question/application/QuestionsQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/QuestionRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/QuestionsRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/QuestionJpaRepository.java
Labels: refactor

#102 feature/#100 강의자료 업로드 및 다운로드 기능 구현
  jacoco.gradle
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/application/FileAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/FileAdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/FileAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/application/LectureAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/LectureAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/request/LectureCreateRequest.java
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-admin/src/testFixtures/java/lecture.application/LectureUserAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/application/FileFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/application/FileResource.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/presentation/FileController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/presentation/FileControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponseByAll.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponseByDate.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/speaker/presentation/SpeakerController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/speaker/presentation/SpeakerControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/speaker/presentation/response/SpeakerDetailResponse.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/application/FileStorageService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/application/SpeakerCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/application/SpeakerQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/domain/Speaker.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/exception/SpeakerDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/exception/SpeakerNotFoundException.java
  saerojinro-domain/src/testFixtures/java/lecture/LectureDomainTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/logevent/application/LogEventServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeSpeakerRepository.java
  saerojinro-domain/src/testFixtures/java/speaker/SpeakerDomainTest.java
  saerojinro-domain/src/testFixtures/java/speaker/application/SpeakerCommandServiceTest.java
Labels: feature

#104 feature/#103 즐겨찾기 시간대 별 조회 기능 구현
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/application/WishListFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListControllerImpl.java
  saerojinro-api/src/testFixtures/java/wishList/WishListFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/application/WishListQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/wishlist/domain/WishListRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeWishListRepository.java
  saerojinro-domain/src/testFixtures/java/wishlist/application/WishListQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/WishListRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/WishListJpaRepository.java
Labels: feature

#107 feature/#106 대시보드 시간별 데이터 예상 인원 수 추가
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/response/DashboardResponse.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/response/TimeRankResponse.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/dashboard/application/DashboardService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/dashboard/dto/DashboardAggregation.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/dashboard/dto/TimeRankDto.java
  saerojinro-domain/src/testFixtures/java/dashboard/application/DashboardServiceTest.java
Labels: feature

#110 refactor/#109 강의 추천 로직 최적화
  saerojinro-admin/src/testFixtures/java/lecture.application/LectureAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/application/ReservationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/application/WishListFacade.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureRecommendationService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/application/LogEventService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/LogEvent.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/LogEventProducer.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/LogEventRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/dto/RedisLogEvent.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureRecommendationServiceTest.java
  saerojinro-domain/src/testFixtures/java/logevent/application/LogEventServiceTest.java
  saerojinro-domain/src/testFixtures/java/logevent/domain/LogEventDomainTest.java
  saerojinro-domain/src/testFixtures/java/mock/producer/FakeLogEventProducer.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLogEventRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/messaging/eventlog/LogEventProducerImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/messaging/eventlog/RedisStreamListener.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LogEventRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/EventLogJpaRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LogEventJpaRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/redis/RedisLogEventRepository.java
Labels: refactor

#113 feature/#98 예약 생성 락 적용
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/application/ReservationFacade.java
  saerojinro-api/src/testFixtures/java/reservation/ReservationFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/LectureRepository.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/exception/ReservationDomainExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/exception/ReservationExistException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/exception/ReservationFullException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/exception/ReservationNotFoundException.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLectureRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LectureRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
Labels: feature

#116 feature/#115 해당 시간대 인기 강의 추천 구현
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/notification/application/NotificationScheduler.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureRecommendationService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/application/LogEventService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/LogEventRepository.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureRecommendationServiceTest.java
  saerojinro-domain/src/testFixtures/java/logevent/application/LogEventServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLogEventRepository.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LogEventRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LogEventJpaRepository.java
Labels: refactor

#120 feature/#117 모니터링 설정
  .gitignore
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-api/src/main/resources/application.yml
  saerojinro-auth/src/main/resources/application.yml
  saerojinro-infra/build.gradle
Labels: feature

#119 refactor/#118 시간대별 즐겨찾기 수정
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/application/WishListFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListControllerImpl.java
  saerojinro-api/src/testFixtures/java/wishList/WishListFacadeTest.java
Labels: refactor

#126 feature/#111 async notifiation
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/config/InfraConfig.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/response/LectureCreateResponse.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/notification/application/NotificationAdminEventHandler.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/notification/application/NotificationAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/notification/application/NotificationScheduler.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/notification/exception/NotificationApiExceptionCode.java
  saerojinro-admin/src/testFixtures/java/notification/application/NotificationUserAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/config/InfraConfig.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/response/ReservationCreateResponse.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/config/InfraConfig.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/application/EmitterQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/exception/EmitterNotFoundException.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/notification/exception/NotificationDomainExceptionCode.java
  saerojinro-domain/src/testFixtures/java/notification/application/EmitterQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/SaeroJinroConfigGroup.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/AsyncConfig.java
Labels: feature

#125 feature/#123 강연자 조회시 현재 강의 리스트 반환
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/request/LectureCreateRequest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/application/FileFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/presentation/FileController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/presentation/FileControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureSummaryResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/speaker/presentation/SpeakerController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/speaker/presentation/SpeakerControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/speaker/presentation/response/SpeakerDetailResponse.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/application/SpeakerQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/speaker/domain/Speaker.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeLectureRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeSpeakerRepository.java
  saerojinro-domain/src/testFixtures/java/speaker/application/SpeakerQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
Labels: feature

#133 chore/#62 예시 데이터 추가
  saerojinro-api/src/main/resources/db/data.sql
  saerojinro-api/src/main/resources/db/schema.sql
Labels: chore

#134 refactor/#130 강의 데이터 캐싱 적용
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/SaerojinroAdminApplication.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/config/InfraConfig.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/SaerojinroApiApplication.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/config/InfraConfig.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/application/QuestionFacade.java
  saerojinro-api/src/main/resources/application.yml
  saerojinro-domain/build.gradle
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/dto/LectureCacheDTO.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/dto/LectureCacheListDTO.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/application/QuestionQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/question/domain/QuestionRepository.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureQueryServiceTest.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeQuestionRepository.java
  saerojinro-domain/src/testFixtures/java/question/application/QuestionsQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/RedisConfig.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/QuestionRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/QuestionJpaRepository.java
Labels: refactor

#131 refactor/#128 시간표 현재 예약 수 캐싱
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/application/ReservationCountScheduler.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/application/TimetableFacade.java
  saerojinro-api/src/testFixtures/java/timetable/ReservationCountSchedulerTest.java
  saerojinro-api/src/testFixtures/java/timetable/TimetableFacadeTest.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/application/ReservationQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/reservation/domain/ReservationRepository.java
  saerojinro-domain/src/testFixtures/java/mock/repository/FakeReservationRepository.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/reservation/application/ReservationQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/ReservationRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/redis/RedisReservationCountRepository.java
Labels: refactor

#132 feature/#114 CI/CD 구현
  .github/workflows/build-deploy.yml
Labels: feature

#138 refactor/#136 유저 데이터 캐싱
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/RedisConfig.java
Labels: refactor

#140 refactor/#139 즐겨찾기 조회 및 강의 추천 API QA
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureSummaryResponse.java
Labels: refactor

#142 fix/#141 강의 상세 조회 에러 수정
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/dto/LectureCacheDTO.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/redis/RedisConfig.java
Labels: bug

#143 Refactor/#135 s3 버킷 연동 및 강의 생성시 캐시 초기화
  build.gradle
  saerojinro-admin/src/main/resources/applicaiton-prod.yml
  saerojinro-admin/src/main/resources/application.yml
  saerojinro-admin/src/testFixtures/java/file/application/FileAdminFacadeTest.java
  saerojinro-admin/src/testFixtures/java/lecture.application/LectureAdminFacadeTest.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/application/FileFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/application/FileResource.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/presentation/FileControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureDetailResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/response/LectureSummaryResponse.java
  saerojinro-api/src/main/resources/application-prod.yml
  saerojinro-api/src/main/resources/application.yml
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/file/application/FileStorageService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/application/LectureCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/file/FileDomainTest.java
  saerojinro-domain/src/testFixtures/java/file/application/FileCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/file/application/FileStorageServiceTest.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/config/AwsS3Config.java
Labels: refactor

#145 fix/#144 레디스 직렬화
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/BaseTimeEntity.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/User.java
Labels: bug

#147 fix/#145 날짜 형식 수정
  saerojinro-common/src/main/java/goorm/saerojinro/common/domain/BaseTimeEntity.java
Labels: bug

#151 feat/#149 강의 전체 조회 기능 구현
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/application/LectureAdminFacade.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/LectureAdminController.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/LectureAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/response/LectureIdNameMappingListResponse.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/response/LectureIdNameMappingResponse.java
  saerojinro-admin/src/testFixtures/java/lecture.application/LectureAdminFacadeTest.java
Labels: feature

#155 fix/#154 삭제된 강의 조회 제외 및 강의 DDL 수정
  saerojinro-api/src/main/resources/db/schema.sql
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/lecture/domain/Lecture.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/LectureRepositoryImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/jpa/LectureJpaRepository.java
Labels: bug

#159 refactor/#158 subscribe 시 SseEmitter 반환
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationControllerImpl.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/notification/sse/NotificationSseSender.java
  saerojinro-infra/src/main/java/goorm/saerojinro/infra/repository/impl/EmitterRepositoryImpl.java
Labels: refactor

#163 refactor/#162 무중단 배포 설정
  .github/workflows/build-deploy.yml
Labels: refactor

#165 fix/#164 CORS PATCH 에러 해결
  saerojinro-common/src/main/java/goorm/saerojinro/common/config/SecurityConfig.java
Labels: bug

#167 refactor/#166 즐겨찾기 정보 조회 시 강의 아이디 추가
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/response/WishListDetailResponse.java
Labels: refactor

#169 refactor/#168 api 권한 체크 추가
  .github/workflows/pull-request-test-coverage.yml
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/dashboard/presentation/DashboardControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/file/presentation/FileAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/lecture/presentation/LectureAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/notification/presentation/NotificationAdminControllerImpl.java
  saerojinro-admin/src/main/java/goorm/saerojinro/admin/api/user/presentation/UserAdminControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/file/presentation/FileControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/application/LectureFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/lecture/presentation/LectureControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/notification/presentation/NotificationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/QuestionControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/application/ReservationFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/reservation/presentation/ReservationControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/speaker/presentation/SpeakerControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/timetable/presentation/TimetableControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/UserControllerImpl.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/application/WishListFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/wishlist/presentation/WishListControllerImpl.java
  saerojinro-api/src/testFixtures/java/lecture/LectureFacadeTest.java
  saerojinro-api/src/testFixtures/java/reservation/ReservationFacadeTest.java
  saerojinro-api/src/testFixtures/java/wishList/WishListFacadeTest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/AuthControllerImpl.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/exception/GlobalExceptionCode.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/application/LogEventService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/logevent/domain/dto/RedisLogEvent.java
  saerojinro-domain/src/testFixtures/java/lecture/application/LectureRecommendationServiceTest.java
  saerojinro-domain/src/testFixtures/java/logevent/application/LogEventServiceTest.java
Labels: refactor

#173 fix/#172 유저 정보 수정 에러
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/application/UserFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/response/UserInfoResponse.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/application/AuthFacade.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/social/dto/SocialUserProfile.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserCommandService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/testFixtures/java/user/application/UserCommandServiceTest.java
  saerojinro-domain/src/testFixtures/java/user/application/UserQueryServiceTest.java
Labels: refactor

#171 refactor/#170 question 응답 객체 QA
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/application/QuestionFacade.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/QuestionController.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/response/QuestionListResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/question/presentation/response/QuestionResponse.java
  saerojinro-api/src/main/java/goorm/saerojinro/api/user/presentation/response/UserInfoResponse.java
Labels: refactor

#175 fix/#174 AuthController 권한 변경
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/presentation/AuthControllerImpl.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/exception/GlobalExceptionHandler.java
Labels: refactor

#177 chore/#176 readme 변경
  .github/images/cicd_pipeline.png
  .github/images/multimodule.png
  README.md
Labels: chore

#179 refactor/#178 jwt payload subject 수정
  saerojinro-api/src/testFixtures/java/reservation/ReservationFacadeTest.java
  saerojinro-api/src/testFixtures/java/timetable/TimetableFacadeTest.java
  saerojinro-auth/src/main/java/goorm/saerojinro/auth/api/application/AuthFacade.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/exception/GlobalExceptionHandler.java
  saerojinro-common/src/main/java/goorm/saerojinro/common/jwt/JwtProvider.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/application/UserQueryService.java
  saerojinro-domain/src/main/java/goorm/saerojinro/domain/user/domain/User.java
  saerojinro-domain/src/testFixtures/java/user/UserDomainTest.java
Labels: refactor
